import Navbar from "../shared/widget/navbar/Navbar";
import { lato } from "./fonts";
import "./global.css";

export const metadata = {
  title: "Welcome to user-ui",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.className} bg-gray-50`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
