import { lato } from "./fonts";
import Provider from "./providers";
import "./global.css";

export const metadata = {
  title: "Welcome to user-ui",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${lato.className} bg-gray-50`}>
      <Provider>
        <body>{children}</body>
      </Provider>
    </html>
  );
}
